### ISSUE TITLE
Readme confusing

### ISSUE THREAD

**Issue by joyously** [elmsln/wp-plugin-hax#5]
The readme looks like a copy of a previous readme for a different platform.
It makes no sense in the context of WordPress.

```
Usage

This should give you the dependencies you need to get going.

    Enable the HAX module and any dependencies it requires.
    Go to the permissions page to ensure users have the 'use hax' permission checked. Once this 
is checked then people will start to see a 'HAX Authoring' local menu item / tab / contextual option 
show up when they have access to edit a node. If you want users to be able to upload files, grant 
the 'Upload files via HAX editor' permission.
```

Can you say what this plugin does?
What is the HAX module?
Can you say what dependencies there are, and where to find them?
What permissions page?
What is a node?
How do I get to HAX to edit? (Where is this local menu item?)
Where do I grant permission to upload files?

**Comment by btopro** [comment]
Great questions @joyously and thank you for posting. I've rewritten the directions to hopefully make more sense in a WordPress context. Let me know if it makes more sense now -- https://github.com/elmsln/wp-plugin-hax

**Comment by joyously** [comment]
That is much better!
I got the plugin doing something now! I didn't have the other plugin needed, because nothing said it was required. Why are they two separate plugins? Why doesn't this one check for the other one and give some error message that it is needed?

**Comment by btopro** [comment]
is there an article or example you could point me to as to setting the dependencies in the file. Webcomponents is for getting compiled webcomponents loaded. HAX is focused on the editor only

**Comment by joyously** [comment]
WordPress doesn't have any dependency management for plugins. It's only for scripts and styles that are enqueued.
But you can always do `function_exists` and `add_action` for `admin_notices`.
https://developer.wordpress.org/?s=admin_notices
or make one plugin instead of two for this platform
