### ISSUE TITLE
Plugin does nothing

### ISSUE THREAD

**Issue by joyously** [elmsln/wp-plugin-hax#6]
https://github.com/elmsln/wp-plugin-hax/blob/f47a68c3e2e3dd152bfcecd8b0b8b856da9da5b3/hax.php#L21

This should be
`wp_enqueue_script( 'hax_the_press', plugins_url('js/hax-the-press.js', __FILE__), array(), false, true ); `

**Comment by btopro** [comment]
thank you, it was working for me locally but I'll assume that this fixes some possible pathing issue based on where it's installed.
